feat(deploy): added kubernetes deploy
FIS2425/api-gateway pull request #38
Opened 2024-11-27 14:56 UTC by adrrf

This pull request introduces new Kubernetes configurations for the `api-gateway` service, including a PersistentVolumeClaim, Deployment, and Service. These changes are essential for setting up the `api-gateway` service within a Kubernetes cluster.

Kubernetes configurations:

* Added a PersistentVolumeClaim to request 100Mi of storage for the `api-gateway-data` service in `kubernetes/api-gateway-data-persistentvolumeclaim.yaml`.
* Created a Deployment for the `api-gateway` service with one replica, using the `ghcr.io/fis2425/api-gateway:latest` image in `kubernetes/api-gateway-deployment.yaml`.
* Defined a LoadBalancer Service for the `api-gateway` to expose port 8080 in `kubernetes/api-gateway-service.yaml`.

2024-11-27 20:27 UTC, AntonioRodriguezRuiz requested changes

2024-11-27 20:27 UTC, AntonioRodriguezRuiz commented on kubernetes/api-gateway-service.yaml
> +      targetPort: 8080
You need to add a nodePort if you want to stablish a static given port when exposing it outside of kubernetes. This is essential if we need to communicate with it

2024-11-28 08:58 UTC, adrrf commented on kubernetes/api-gateway-service.yaml
> +      targetPort: 8080
this is not needed as the deploy is going to be done in the same cluster no?

2024-11-28 14:27 UTC, AntonioRodriguezRuiz approved these changes

2024-11-28 16:07 UTC, merged